apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080  # Optional: You can specify a specific port number or leave it out for automatic allocation.
  type: NodePort

